disabled_rules:
 - control_statement
 - comma
 - identifier_name
line_length:
 - 300 # error

force_cast:
 severity: warning # explicity

nesting:
 type_level: 3

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
